CREATE DATABASE IF NOT EXISTS back_office_db;
CREATE DATABASE IF NOT EXISTS wallet;
CREATE DATABASE IF NOT EXISTS reporting_service_db;
CREATE DATABASE IF NOT EXISTS reporting_service;
CREATE DATABASE IF NOT EXISTS activity_logs_db;
CREATE DATABASE IF NOT EXISTS player_db;

ALTER USER IF EXISTS 'admin'@'%' IDENTIFIED BY 'DevServer1!' REQUIRE SSL;
ALTER USER IF EXISTS 'admin'@'localhost' IDENTIFIED BY 'DevServer1!' REQUIRE SSL;

CREATE USER IF NOT EXISTS 'dev'@'%' IDENTIFIED BY 'DevServer1!' REQUIRE NONE;
CREATE USER IF NOT EXISTS 'dev'@'localhost' IDENTIFIED BY 'DevServer1!' REQUIRE NONE;
